"""Parsed AST data models for the Semantic Translation Layer.

These models represent the output of the STL parser — a structured,
type-safe intermediate form ready for storage.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ParseLevel(str, Enum):
    """How a line was successfully parsed (traceability tag)."""
    STRICT = "strict"
    FUZZY = "fuzzy"
    LLM_CORRECTED = "llm_corrected"
    FALLBACK = "fallback"


class RefScope(str, Enum):
    """Scope of an entity reference."""
    SELF = "self"
    LOCAL = "local"
    WORLD = "world"
    BLANK = "blank"
    UNKNOWN = "unknown"  # fallback for undeclared refs


class VocabCategory(str, Enum):
    """Category of a predicate in the vocabulary registry."""
    PROP = "prop"
    FRAME = "frame"
    QUALIFIER = "qualifier"
    REF_TYPE = "ref_type"


# ---------------------------------------------------------------------------
# Ref Expression
# ---------------------------------------------------------------------------

class RefExpr(BaseModel):
    """Parsed entity reference expression (right-hand side of @id = ...)."""
    scope: RefScope
    ref_type: Optional[str] = None   # "person", "place", etc.
    key: Optional[str] = None        # "tom", "tokyo", etc.
    aliases: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Parsed Argument Types (union discriminated by 'kind')
# ---------------------------------------------------------------------------

class RefArg(BaseModel):
    """Argument referencing an entity: @id."""
    kind: str = "ref"
    ref_id: str   # local alias like "s", "t"


class PropArg(BaseModel):
    """Argument referencing a proposition/frame: $id."""
    kind: str = "prop"
    prop_id: str  # local alias like "p1", "f1"


class LiteralArg(BaseModel):
    """String literal argument: "text"."""
    kind: str = "literal"
    value: str


class NumberArg(BaseModel):
    """Numeric argument: 42, 0.8."""
    kind: str = "number"
    value: float


class ListArg(BaseModel):
    """List argument: [a, b, c]."""
    kind: str = "list"
    items: List[ParsedArg]


class InlinePredArg(BaseModel):
    """Inline predicate argument: pred(args...) — before expansion."""
    kind: str = "inline_pred"
    predicate: str
    args: List[ParsedArg]


# Union type for all argument kinds
ParsedArg = Union[RefArg, PropArg, LiteralArg, NumberArg, ListArg, InlinePredArg]

# Pydantic needs forward-ref update for recursive models
ListArg.model_rebuild()
InlinePredArg.model_rebuild()


# ---------------------------------------------------------------------------
# Parsed Line Types
# ---------------------------------------------------------------------------

class ParsedRef(BaseModel):
    """Parsed REF line: @id = ref_expression."""
    local_id: str            # "s", "t", etc.
    expr: RefExpr
    parse_level: ParseLevel = ParseLevel.STRICT


class ParsedStatement(BaseModel):
    """Parsed PROP or FRAME line: $id = predicate(args...)."""
    local_id: str            # "p1", "f1", etc.
    predicate: str           # "friend", "hope", etc.
    args: List[ParsedArg]
    category: Optional[str] = None  # "prop" | "frame" | "qualifier" — set post-parse
    parse_level: ParseLevel = ParseLevel.STRICT
    is_auto_expanded: bool = False  # True for $_autoN generated by inline expansion


class ParsedEvidence(BaseModel):
    """Parsed EV line: ev($target, conf=N, span="...")."""
    target_local_id: str     # "p1", "f1"
    conf: float
    span: Optional[str] = None
    residual: Optional[str] = None
    parse_level: ParseLevel = ParseLevel.STRICT


class ParsedNote(BaseModel):
    """Parsed NOTE line: note($target, "text")."""
    target_local_id: str     # "p1"
    text: str
    parse_level: ParseLevel = ParseLevel.STRICT


class FailedLine(BaseModel):
    """A line that failed all parse levels — preserved for diagnostics."""
    line_number: int
    raw_text: str
    error: str


# ---------------------------------------------------------------------------
# Top-level Parse Result
# ---------------------------------------------------------------------------

class ParsedProgram(BaseModel):
    """Complete parse result for one extraction batch."""
    batch_id: str
    refs: List[ParsedRef] = Field(default_factory=list)
    statements: List[ParsedStatement] = Field(default_factory=list)
    evidence: List[ParsedEvidence] = Field(default_factory=list)
    notes: List[ParsedNote] = Field(default_factory=list)
    failed_lines: List[FailedLine] = Field(default_factory=list)

    @property
    def ref_ids(self) -> set:
        """Set of declared local ref IDs."""
        return {r.local_id for r in self.refs}


# ---------------------------------------------------------------------------
# Storage Result
# ---------------------------------------------------------------------------

class StorageResult(BaseModel):
    """Summary of what was persisted from one ParsedProgram."""
    batch_id: str
    refs_upserted: int = 0
    statements_inserted: int = 0
    evidence_inserted: int = 0
    notes_inserted: int = 0
    vocab_registered: int = 0
    errors: List[str] = Field(default_factory=list)
