"""Phase K capability-layer contracts and adapter protocol."""

from .adapter import (
    CapabilityAdapter,
    CapabilityAdapterDescriptor,
    CapabilityAdapterError,
    invoke_capability,
    supports_capability,
    validate_capability_response,
)
from .answering import generate_answer_text
from .audit import (
    CapabilityAuditCaseResult,
    CapabilityFailureAuditResult,
    CapabilityTraceAuditResult,
    assert_capability_failure_audit,
    assert_capability_trace_audit,
    evaluate_capability_failure_audit,
    evaluate_capability_trace_audit,
)
from .benchmark import (
    CapabilityBenchCaseResult,
    CapabilityBenchmarkResult,
    assert_capability_adapter_bench,
    evaluate_capability_adapter_bench,
)
from .claude_adapter import ClaudeCapabilityAdapter
from .config import (
    CapabilityAuthConfig,
    CapabilityAuthMode,
    CapabilityProviderConfig,
    resolve_capability_provider_config,
)
from .contracts import (
    CAPABILITY_CATALOG,
    AnswerRequest,
    AnswerResponse,
    CapabilityFallbackPolicy,
    CapabilityInvocationTrace,
    CapabilityName,
    CapabilityProviderFamily,
    CapabilityRequest,
    CapabilityResponse,
    OfflineReconstructRequest,
    OfflineReconstructResponse,
    ReflectRequest,
    ReflectResponse,
    SummarizeRequest,
    SummarizeResponse,
    request_model_for,
    response_model_for,
)
from .gate import (
    CapabilityContractAuditResult,
    CapabilityGateResult,
    assert_capability_gate,
    evaluate_capability_contract_audit,
    evaluate_capability_gate,
    write_capability_gate_report_json,
)
from .gemini_adapter import GeminiCapabilityAdapter
from .openai_adapter import OpenAICapabilityAdapter
from .port_adapter import CapabilityPortAdapter as CapabilityPortAdapter
from .reporting import (
    CapabilityProviderCompatibilityReport,
    CapabilityProviderCompatibilitySummary,
    build_capability_provider_compatibility_report,
    evaluate_capability_provider_compatibility_report,
    read_capability_provider_compatibility_report_json,
    write_capability_provider_compatibility_report_json,
)
from .service import (
    CapabilityService,
    CapabilityServiceError,
    DeterministicCapabilityAdapter,
    build_capability_adapters_from_environment,
)

__all__ = [
    "CAPABILITY_CATALOG",
    "AnswerRequest",
    "AnswerResponse",
    "CapabilityAdapter",
    "CapabilityAdapterDescriptor",
    "CapabilityAdapterError",
    "CapabilityAuditCaseResult",
    "CapabilityBenchCaseResult",
    "CapabilityBenchmarkResult",
    "CapabilityAuthConfig",
    "CapabilityAuthMode",
    "CapabilityContractAuditResult",
    "ClaudeCapabilityAdapter",
    "CapabilityFailureAuditResult",
    "CapabilityFallbackPolicy",
    "CapabilityGateResult",
    "CapabilityInvocationTrace",
    "CapabilityName",
    "CapabilityProviderConfig",
    "CapabilityProviderCompatibilityReport",
    "CapabilityProviderCompatibilitySummary",
    "CapabilityProviderFamily",
    "CapabilityRequest",
    "CapabilityResponse",
    "CapabilityService",
    "CapabilityServiceError",
    "CapabilityTraceAuditResult",
    "DeterministicCapabilityAdapter",
    "GeminiCapabilityAdapter",
    "OpenAICapabilityAdapter",
    "OfflineReconstructRequest",
    "OfflineReconstructResponse",
    "ReflectRequest",
    "ReflectResponse",
    "SummarizeRequest",
    "SummarizeResponse",
    "generate_answer_text",
    "build_capability_provider_compatibility_report",
    "build_capability_adapters_from_environment",
    "assert_capability_gate",
    "assert_capability_adapter_bench",
    "assert_capability_failure_audit",
    "assert_capability_trace_audit",
    "evaluate_capability_adapter_bench",
    "evaluate_capability_contract_audit",
    "evaluate_capability_failure_audit",
    "evaluate_capability_gate",
    "evaluate_capability_provider_compatibility_report",
    "evaluate_capability_trace_audit",
    "invoke_capability",
    "read_capability_provider_compatibility_report_json",
    "request_model_for",
    "resolve_capability_provider_config",
    "response_model_for",
    "supports_capability",
    "validate_capability_response",
    "write_capability_gate_report_json",
    "write_capability_provider_compatibility_report_json",
]
